import path from "node:path";
import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { VitePWA } from "vite-plugin-pwa";
import { defineConfig } from "vitest/config";

// Use `Date.now()` instead of `new Date()` to make sure that the time is in `ja-JP` format properly (timezone issues).
const autoGeneratedAppVersion = Intl.DateTimeFormat("ja-JP", {
	dateStyle: "long",
}).format(Date.now());

// https://vitejs.dev/config/
export default defineConfig({
	build: {
		target: "esnext",
	},
	define: {
		"import.meta.env.VITE_APP_VERSION": JSON.stringify(autoGeneratedAppVersion),
	},
	plugins: [
		tailwindcss(),
		react(),
		VitePWA({
			devOptions: {
				enabled: true,
			},
			filename: "sw.ts",
			manifest: {
				background_color: "#f1c40f",
				description: "Speednote, the fastest way to put your quick thoughts!",
				display: "standalone",
				icons: [
					{
						sizes: "64x64 32x32 24x24 16x16",
						src: "icon-64.png",
						type: "image/png",
					},
					{
						sizes: "128x128",
						src: "icon-128.png",
						type: "image/png",
					},
					{
						sizes: "256x256",
						src: "icon-256.png",
						type: "image/png",
					},
					{
						sizes: "512x512",
						src: "icon-512.png",
						type: "image/png",
					},
				],
				name: "Speednote",
				orientation: "portrait",
				short_name: "Speednote",
				start_url: "/",
				theme_color: "#e67e22",
			},
			registerType: "autoUpdate",
			srcDir: "app",
		}),
	],
	resolve: {
		alias: {
			"~": path.resolve(import.meta.dirname, "./app"),
		},
	},
	server: {
		port: 3000,
	},
	test: {
		coverage: {
			exclude: ["app/index.tsx"], // Main function do not need testing.
			include: ["app/**"],
		},
		environment: "jsdom",
		globals: true,
		include: ["__tests__/**/*"],
	},
});
